// ts-gql-integrity:9088535b6300377a032b72cc9520b912
/*
ts-gql-meta-begin
{
  "hash": "0a4fb9889dc52d317a36e1f07b29a21d"
}
ts-gql-meta-end
*/
/** @deprecated This should not be used outside of code generated by ts-gql */
export type Maybe<T> = T | null;
/** @deprecated This should not be used outside of code generated by ts-gql */
export type InputMaybe<T> = Maybe<T>;
/** @deprecated This should not be used outside of code generated by ts-gql */
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** @deprecated This should not be used outside of code generated by ts-gql */
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
/** @deprecated This should not be used outside of code generated by ts-gql */
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };

/** @deprecated This should not be used outside of code generated by ts-gql */
export type Scalars = {
  String: string;
  Int: number;
  Float: number;
  Boolean: boolean;
  ID: string;
  BigInt: BigInt;
  DateTime: DateTime;
  Upload: Upload;
  JSON: JSON;
};

export type Approval = {
  readonly __typename: "Approval";
  readonly id: string;
  readonly code: string | null;
  readonly title: string | null;
  readonly estimatedBudget: BigInt | null;
  readonly description: ReadonlyArray<Description> | null;
  readonly descriptionCount: number | null;
  readonly createdAt: DateTime | null;
  readonly createdBy: User | null;
};

export type ApprovaldescriptionArgs = {
  readonly where?: DescriptionWhereInput;
  readonly orderBy?: TSGQLMaybeArray<DescriptionOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: DescriptionWhereUniqueInput | null;
};

export type ApprovaldescriptionCountArgs = {
  readonly where?: DescriptionWhereInput;
};

export type BigInt = any;

export type DateTime = any;

export type ApprovalWhereUniqueInput = {
  readonly id?: string | null;
};

export type ApprovalWhereInput = {
  readonly AND?: TSGQLMaybeArray<ApprovalWhereInput> | null;
  readonly OR?: TSGQLMaybeArray<ApprovalWhereInput> | null;
  readonly NOT?: TSGQLMaybeArray<ApprovalWhereInput> | null;
  readonly id?: IDFilter | null;
  readonly code?: StringFilter | null;
  readonly title?: StringFilter | null;
  readonly estimatedBudget?: BigIntNullableFilter | null;
  readonly description?: DescriptionManyRelationFilter | null;
  readonly createdAt?: DateTimeNullableFilter | null;
  readonly createdBy?: UserWhereInput | null;
};

export type IDFilter = {
  readonly equals?: string | null;
  readonly in?: TSGQLMaybeArray<string> | null;
  readonly notIn?: TSGQLMaybeArray<string> | null;
  readonly lt?: string | null;
  readonly lte?: string | null;
  readonly gt?: string | null;
  readonly gte?: string | null;
  readonly not?: IDFilter | null;
};

export type StringFilter = {
  readonly equals?: string | null;
  readonly in?: TSGQLMaybeArray<string> | null;
  readonly notIn?: TSGQLMaybeArray<string> | null;
  readonly lt?: string | null;
  readonly lte?: string | null;
  readonly gt?: string | null;
  readonly gte?: string | null;
  readonly contains?: string | null;
  readonly startsWith?: string | null;
  readonly endsWith?: string | null;
  readonly not?: NestedStringFilter | null;
};

export type NestedStringFilter = {
  readonly equals?: string | null;
  readonly in?: TSGQLMaybeArray<string> | null;
  readonly notIn?: TSGQLMaybeArray<string> | null;
  readonly lt?: string | null;
  readonly lte?: string | null;
  readonly gt?: string | null;
  readonly gte?: string | null;
  readonly contains?: string | null;
  readonly startsWith?: string | null;
  readonly endsWith?: string | null;
  readonly not?: NestedStringFilter | null;
};

export type BigIntNullableFilter = {
  readonly equals?: BigInt | null;
  readonly in?: TSGQLMaybeArray<BigInt> | null;
  readonly notIn?: TSGQLMaybeArray<BigInt> | null;
  readonly lt?: BigInt | null;
  readonly lte?: BigInt | null;
  readonly gt?: BigInt | null;
  readonly gte?: BigInt | null;
  readonly not?: BigIntNullableFilter | null;
};

export type DescriptionManyRelationFilter = {
  readonly every?: DescriptionWhereInput | null;
  readonly some?: DescriptionWhereInput | null;
  readonly none?: DescriptionWhereInput | null;
};

export type DateTimeNullableFilter = {
  readonly equals?: DateTime | null;
  readonly in?: TSGQLMaybeArray<DateTime> | null;
  readonly notIn?: TSGQLMaybeArray<DateTime> | null;
  readonly lt?: DateTime | null;
  readonly lte?: DateTime | null;
  readonly gt?: DateTime | null;
  readonly gte?: DateTime | null;
  readonly not?: DateTimeNullableFilter | null;
};

export type ApprovalOrderByInput = {
  readonly id?: OrderDirection | null;
  readonly code?: OrderDirection | null;
  readonly title?: OrderDirection | null;
  readonly estimatedBudget?: OrderDirection | null;
  readonly createdAt?: OrderDirection | null;
};

export type OrderDirection =
  | "asc"
  | "desc";

export type ApprovalUpdateInput = {
  readonly code?: string | null;
  readonly title?: string | null;
  readonly estimatedBudget?: BigInt | null;
  readonly description?: DescriptionRelateToManyForUpdateInput | null;
  readonly createdAt?: DateTime | null;
  readonly createdBy?: UserRelateToOneForUpdateInput | null;
};

export type DescriptionRelateToManyForUpdateInput = {
  readonly disconnect?: TSGQLMaybeArray<DescriptionWhereUniqueInput> | null;
  readonly set?: TSGQLMaybeArray<DescriptionWhereUniqueInput> | null;
  readonly create?: TSGQLMaybeArray<DescriptionCreateInput> | null;
  readonly connect?: TSGQLMaybeArray<DescriptionWhereUniqueInput> | null;
};

export type UserRelateToOneForUpdateInput = {
  readonly create?: UserCreateInput | null;
  readonly connect?: UserWhereUniqueInput | null;
  readonly disconnect?: boolean | null;
};

export type ApprovalUpdateArgs = {
  readonly where: ApprovalWhereUniqueInput;
  readonly data: ApprovalUpdateInput;
};

export type ApprovalCreateInput = {
  readonly code?: string | null;
  readonly title?: string | null;
  readonly estimatedBudget?: BigInt | null;
  readonly description?: DescriptionRelateToManyForCreateInput | null;
  readonly createdAt?: DateTime | null;
  readonly createdBy?: UserRelateToOneForCreateInput | null;
};

export type DescriptionRelateToManyForCreateInput = {
  readonly create?: TSGQLMaybeArray<DescriptionCreateInput> | null;
  readonly connect?: TSGQLMaybeArray<DescriptionWhereUniqueInput> | null;
};

export type UserRelateToOneForCreateInput = {
  readonly create?: UserCreateInput | null;
  readonly connect?: UserWhereUniqueInput | null;
};

export type Description = {
  readonly __typename: "Description";
  readonly id: string;
  readonly subject: string | null;
  readonly title: string | null;
  readonly statements: ReadonlyArray<Statement> | null;
  readonly statementsCount: number | null;
  readonly approvals: Approval | null;
  readonly totalStatementsPayable: string | null;
  readonly totalStatementsPayed: string | null;
  readonly createdAt: DateTime | null;
  readonly createdBy: User | null;
};

export type DescriptionstatementsArgs = {
  readonly where?: StatementWhereInput;
  readonly orderBy?: TSGQLMaybeArray<StatementOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: StatementWhereUniqueInput | null;
};

export type DescriptionstatementsCountArgs = {
  readonly where?: StatementWhereInput;
};

export type DescriptionWhereUniqueInput = {
  readonly id?: string | null;
};

export type DescriptionWhereInput = {
  readonly AND?: TSGQLMaybeArray<DescriptionWhereInput> | null;
  readonly OR?: TSGQLMaybeArray<DescriptionWhereInput> | null;
  readonly NOT?: TSGQLMaybeArray<DescriptionWhereInput> | null;
  readonly id?: IDFilter | null;
  readonly title?: StringFilter | null;
  readonly statements?: StatementManyRelationFilter | null;
  readonly approvals?: ApprovalWhereInput | null;
  readonly createdAt?: DateTimeNullableFilter | null;
  readonly createdBy?: UserWhereInput | null;
};

export type StatementManyRelationFilter = {
  readonly every?: StatementWhereInput | null;
  readonly some?: StatementWhereInput | null;
  readonly none?: StatementWhereInput | null;
};

export type DescriptionOrderByInput = {
  readonly id?: OrderDirection | null;
  readonly title?: OrderDirection | null;
  readonly createdAt?: OrderDirection | null;
};

export type DescriptionUpdateInput = {
  readonly title?: string | null;
  readonly statements?: StatementRelateToManyForUpdateInput | null;
  readonly approvals?: ApprovalRelateToOneForUpdateInput | null;
  readonly createdAt?: DateTime | null;
  readonly createdBy?: UserRelateToOneForUpdateInput | null;
};

export type StatementRelateToManyForUpdateInput = {
  readonly disconnect?: TSGQLMaybeArray<StatementWhereUniqueInput> | null;
  readonly set?: TSGQLMaybeArray<StatementWhereUniqueInput> | null;
  readonly create?: TSGQLMaybeArray<StatementCreateInput> | null;
  readonly connect?: TSGQLMaybeArray<StatementWhereUniqueInput> | null;
};

export type ApprovalRelateToOneForUpdateInput = {
  readonly create?: ApprovalCreateInput | null;
  readonly connect?: ApprovalWhereUniqueInput | null;
  readonly disconnect?: boolean | null;
};

export type DescriptionUpdateArgs = {
  readonly where: DescriptionWhereUniqueInput;
  readonly data: DescriptionUpdateInput;
};

export type DescriptionCreateInput = {
  readonly title?: string | null;
  readonly statements?: StatementRelateToManyForCreateInput | null;
  readonly approvals?: ApprovalRelateToOneForCreateInput | null;
  readonly createdAt?: DateTime | null;
  readonly createdBy?: UserRelateToOneForCreateInput | null;
};

export type StatementRelateToManyForCreateInput = {
  readonly create?: TSGQLMaybeArray<StatementCreateInput> | null;
  readonly connect?: TSGQLMaybeArray<StatementWhereUniqueInput> | null;
};

export type ApprovalRelateToOneForCreateInput = {
  readonly create?: ApprovalCreateInput | null;
  readonly connect?: ApprovalWhereUniqueInput | null;
};

export type Statement = {
  readonly __typename: "Statement";
  readonly id: string;
  readonly confirmedByTheUploader: boolean | null;
  readonly title: string | null;
  readonly description: Description | null;
  readonly sateOfStatement: number | null;
  readonly image: ImageFieldOutput | null;
  readonly items: ReadonlyArray<StatementItem> | null;
  readonly itemsCount: number | null;
  readonly peyments: ReadonlyArray<Payment> | null;
  readonly peymentsCount: number | null;
  readonly deductionOnAccountOfAdvancePayment: BigInt | null;
  readonly tax: BigInt | null;
  readonly totalPayable: string | null;
  readonly status: string | null;
  readonly createdAt: DateTime | null;
  readonly createdBy: User | null;
  readonly updatedBy: User | null;
};

export type StatementitemsArgs = {
  readonly where?: StatementItemWhereInput;
  readonly orderBy?: TSGQLMaybeArray<StatementItemOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: StatementItemWhereUniqueInput | null;
};

export type StatementitemsCountArgs = {
  readonly where?: StatementItemWhereInput;
};

export type StatementpeymentsArgs = {
  readonly where?: PaymentWhereInput;
  readonly orderBy?: TSGQLMaybeArray<PaymentOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: PaymentWhereUniqueInput | null;
};

export type StatementpeymentsCountArgs = {
  readonly where?: PaymentWhereInput;
};

export type ImageFieldOutput = {
  readonly __typename: "ImageFieldOutput";
  readonly id: string;
  readonly filesize: number;
  readonly width: number;
  readonly height: number;
  readonly extension: ImageExtension;
  readonly url: string;
};

export type ImageExtension =
  | "jpg"
  | "png"
  | "webp"
  | "gif";

export type StatementWhereUniqueInput = {
  readonly id?: string | null;
};

export type StatementWhereInput = {
  readonly AND?: TSGQLMaybeArray<StatementWhereInput> | null;
  readonly OR?: TSGQLMaybeArray<StatementWhereInput> | null;
  readonly NOT?: TSGQLMaybeArray<StatementWhereInput> | null;
  readonly id?: IDFilter | null;
  readonly confirmedByTheUploader?: BooleanFilter | null;
  readonly title?: StringFilter | null;
  readonly description?: DescriptionWhereInput | null;
  readonly sateOfStatement?: PairFilter | null;
  readonly items?: StatementItemManyRelationFilter | null;
  readonly peyments?: PaymentManyRelationFilter | null;
  readonly deductionOnAccountOfAdvancePayment?: BigIntNullableFilter | null;
  readonly tax?: BigIntFilter | null;
  readonly status?: StringNullableFilter | null;
  readonly createdAt?: DateTimeNullableFilter | null;
  readonly createdBy?: UserWhereInput | null;
  readonly updatedBy?: UserWhereInput | null;
};

export type BooleanFilter = {
  readonly equals?: boolean | null;
  readonly not?: BooleanFilter | null;
};

export type PairFilter = {
  readonly equals?: number | null;
  readonly lt?: number | null;
  readonly lte?: number | null;
  readonly gt?: number | null;
  readonly gte?: number | null;
};

export type StatementItemManyRelationFilter = {
  readonly every?: StatementItemWhereInput | null;
  readonly some?: StatementItemWhereInput | null;
  readonly none?: StatementItemWhereInput | null;
};

export type PaymentManyRelationFilter = {
  readonly every?: PaymentWhereInput | null;
  readonly some?: PaymentWhereInput | null;
  readonly none?: PaymentWhereInput | null;
};

export type BigIntFilter = {
  readonly equals?: BigInt | null;
  readonly in?: TSGQLMaybeArray<BigInt> | null;
  readonly notIn?: TSGQLMaybeArray<BigInt> | null;
  readonly lt?: BigInt | null;
  readonly lte?: BigInt | null;
  readonly gt?: BigInt | null;
  readonly gte?: BigInt | null;
  readonly not?: BigIntFilter | null;
};

export type StringNullableFilter = {
  readonly equals?: string | null;
  readonly in?: TSGQLMaybeArray<string> | null;
  readonly notIn?: TSGQLMaybeArray<string> | null;
  readonly lt?: string | null;
  readonly lte?: string | null;
  readonly gt?: string | null;
  readonly gte?: string | null;
  readonly contains?: string | null;
  readonly startsWith?: string | null;
  readonly endsWith?: string | null;
  readonly not?: StringNullableFilter | null;
};

export type StatementOrderByInput = {
  readonly id?: OrderDirection | null;
  readonly confirmedByTheUploader?: OrderDirection | null;
  readonly title?: OrderDirection | null;
  readonly sateOfStatement?: OrderDirection | null;
  readonly deductionOnAccountOfAdvancePayment?: OrderDirection | null;
  readonly tax?: OrderDirection | null;
  readonly status?: OrderDirection | null;
  readonly createdAt?: OrderDirection | null;
};

export type StatementUpdateInput = {
  readonly confirmedByTheUploader?: boolean | null;
  readonly title?: string | null;
  readonly description?: DescriptionRelateToOneForUpdateInput | null;
  readonly sateOfStatement?: number | null;
  readonly image?: ImageFieldInput | null;
  readonly items?: StatementItemRelateToManyForUpdateInput | null;
  readonly peyments?: PaymentRelateToManyForUpdateInput | null;
  readonly deductionOnAccountOfAdvancePayment?: BigInt | null;
  readonly tax?: BigInt | null;
  readonly status?: string | null;
  readonly createdAt?: DateTime | null;
  readonly createdBy?: UserRelateToOneForUpdateInput | null;
  readonly updatedBy?: UserRelateToOneForUpdateInput | null;
};

export type DescriptionRelateToOneForUpdateInput = {
  readonly create?: DescriptionCreateInput | null;
  readonly connect?: DescriptionWhereUniqueInput | null;
  readonly disconnect?: boolean | null;
};

export type ImageFieldInput = {
  readonly upload: Upload;
};

export type Upload = any;

export type StatementItemRelateToManyForUpdateInput = {
  readonly disconnect?: TSGQLMaybeArray<StatementItemWhereUniqueInput> | null;
  readonly set?: TSGQLMaybeArray<StatementItemWhereUniqueInput> | null;
  readonly create?: TSGQLMaybeArray<StatementItemCreateInput> | null;
  readonly connect?: TSGQLMaybeArray<StatementItemWhereUniqueInput> | null;
};

export type PaymentRelateToManyForUpdateInput = {
  readonly disconnect?: TSGQLMaybeArray<PaymentWhereUniqueInput> | null;
  readonly set?: TSGQLMaybeArray<PaymentWhereUniqueInput> | null;
  readonly create?: TSGQLMaybeArray<PaymentCreateInput> | null;
  readonly connect?: TSGQLMaybeArray<PaymentWhereUniqueInput> | null;
};

export type StatementUpdateArgs = {
  readonly where: StatementWhereUniqueInput;
  readonly data: StatementUpdateInput;
};

export type StatementCreateInput = {
  readonly confirmedByTheUploader?: boolean | null;
  readonly title?: string | null;
  readonly description?: DescriptionRelateToOneForCreateInput | null;
  readonly sateOfStatement?: number | null;
  readonly image?: ImageFieldInput | null;
  readonly items?: StatementItemRelateToManyForCreateInput | null;
  readonly peyments?: PaymentRelateToManyForCreateInput | null;
  readonly deductionOnAccountOfAdvancePayment?: BigInt | null;
  readonly tax?: BigInt | null;
  readonly status?: string | null;
  readonly createdAt?: DateTime | null;
  readonly createdBy?: UserRelateToOneForCreateInput | null;
  readonly updatedBy?: UserRelateToOneForCreateInput | null;
};

export type DescriptionRelateToOneForCreateInput = {
  readonly create?: DescriptionCreateInput | null;
  readonly connect?: DescriptionWhereUniqueInput | null;
};

export type StatementItemRelateToManyForCreateInput = {
  readonly create?: TSGQLMaybeArray<StatementItemCreateInput> | null;
  readonly connect?: TSGQLMaybeArray<StatementItemWhereUniqueInput> | null;
};

export type PaymentRelateToManyForCreateInput = {
  readonly create?: TSGQLMaybeArray<PaymentCreateInput> | null;
  readonly connect?: TSGQLMaybeArray<PaymentWhereUniqueInput> | null;
};

export type StatementItem = {
  readonly __typename: "StatementItem";
  readonly id: string;
  readonly description: string | null;
  readonly unit: string | null;
  readonly unitPrice: number | null;
  readonly quantity: number | null;
  readonly percentageOfWorkDone: number | null;
  readonly total: string | null;
  readonly statement: Statement | null;
};

export type StatementItemWhereUniqueInput = {
  readonly id?: string | null;
};

export type StatementItemWhereInput = {
  readonly AND?: TSGQLMaybeArray<StatementItemWhereInput> | null;
  readonly OR?: TSGQLMaybeArray<StatementItemWhereInput> | null;
  readonly NOT?: TSGQLMaybeArray<StatementItemWhereInput> | null;
  readonly id?: IDFilter | null;
  readonly description?: StringFilter | null;
  readonly unit?: StringNullableFilter | null;
  readonly unitPrice?: IntFilter | null;
  readonly quantity?: IntFilter | null;
  readonly percentageOfWorkDone?: IntNullableFilter | null;
  readonly statement?: StatementWhereInput | null;
};

export type IntFilter = {
  readonly equals?: number | null;
  readonly in?: TSGQLMaybeArray<number> | null;
  readonly notIn?: TSGQLMaybeArray<number> | null;
  readonly lt?: number | null;
  readonly lte?: number | null;
  readonly gt?: number | null;
  readonly gte?: number | null;
  readonly not?: IntFilter | null;
};

export type IntNullableFilter = {
  readonly equals?: number | null;
  readonly in?: TSGQLMaybeArray<number> | null;
  readonly notIn?: TSGQLMaybeArray<number> | null;
  readonly lt?: number | null;
  readonly lte?: number | null;
  readonly gt?: number | null;
  readonly gte?: number | null;
  readonly not?: IntNullableFilter | null;
};

export type StatementItemOrderByInput = {
  readonly id?: OrderDirection | null;
  readonly description?: OrderDirection | null;
  readonly unit?: OrderDirection | null;
  readonly unitPrice?: OrderDirection | null;
  readonly quantity?: OrderDirection | null;
  readonly percentageOfWorkDone?: OrderDirection | null;
};

export type StatementItemUpdateInput = {
  readonly description?: string | null;
  readonly unit?: string | null;
  readonly unitPrice?: number | null;
  readonly quantity?: number | null;
  readonly percentageOfWorkDone?: number | null;
  readonly statement?: StatementRelateToOneForUpdateInput | null;
};

export type StatementRelateToOneForUpdateInput = {
  readonly create?: StatementCreateInput | null;
  readonly connect?: StatementWhereUniqueInput | null;
  readonly disconnect?: boolean | null;
};

export type StatementItemUpdateArgs = {
  readonly where: StatementItemWhereUniqueInput;
  readonly data: StatementItemUpdateInput;
};

export type StatementItemCreateInput = {
  readonly description?: string | null;
  readonly unit?: string | null;
  readonly unitPrice?: number | null;
  readonly quantity?: number | null;
  readonly percentageOfWorkDone?: number | null;
  readonly statement?: StatementRelateToOneForCreateInput | null;
};

export type StatementRelateToOneForCreateInput = {
  readonly create?: StatementCreateInput | null;
  readonly connect?: StatementWhereUniqueInput | null;
};

export type Payment = {
  readonly __typename: "Payment";
  readonly id: string;
  readonly title: string | null;
  readonly dateOfPayment: number | null;
  readonly statement: Statement | null;
  readonly description: string | null;
  readonly price: BigInt | null;
  readonly attachment: ImageFieldOutput | null;
};

export type PaymentWhereUniqueInput = {
  readonly id?: string | null;
};

export type PaymentWhereInput = {
  readonly AND?: TSGQLMaybeArray<PaymentWhereInput> | null;
  readonly OR?: TSGQLMaybeArray<PaymentWhereInput> | null;
  readonly NOT?: TSGQLMaybeArray<PaymentWhereInput> | null;
  readonly id?: IDFilter | null;
  readonly title?: StringFilter | null;
  readonly dateOfPayment?: PairFilter | null;
  readonly statement?: StatementWhereInput | null;
  readonly description?: StringFilter | null;
  readonly price?: BigIntNullableFilter | null;
};

export type PaymentOrderByInput = {
  readonly id?: OrderDirection | null;
  readonly title?: OrderDirection | null;
  readonly dateOfPayment?: OrderDirection | null;
  readonly description?: OrderDirection | null;
  readonly price?: OrderDirection | null;
};

export type PaymentUpdateInput = {
  readonly title?: string | null;
  readonly dateOfPayment?: number | null;
  readonly statement?: StatementRelateToOneForUpdateInput | null;
  readonly description?: string | null;
  readonly price?: BigInt | null;
  readonly attachment?: ImageFieldInput | null;
};

export type PaymentUpdateArgs = {
  readonly where: PaymentWhereUniqueInput;
  readonly data: PaymentUpdateInput;
};

export type PaymentCreateInput = {
  readonly title?: string | null;
  readonly dateOfPayment?: number | null;
  readonly statement?: StatementRelateToOneForCreateInput | null;
  readonly description?: string | null;
  readonly price?: BigInt | null;
  readonly attachment?: ImageFieldInput | null;
};

export type ImageStore = {
  readonly __typename: "ImageStore";
  readonly id: string;
  readonly url: string | null;
  readonly image: ImageFieldOutput | null;
  readonly altText: string | null;
  readonly createdAt: DateTime | null;
};

export type ImageStoreWhereUniqueInput = {
  readonly id?: string | null;
};

export type ImageStoreWhereInput = {
  readonly AND?: TSGQLMaybeArray<ImageStoreWhereInput> | null;
  readonly OR?: TSGQLMaybeArray<ImageStoreWhereInput> | null;
  readonly NOT?: TSGQLMaybeArray<ImageStoreWhereInput> | null;
  readonly id?: IDFilter | null;
  readonly altText?: StringFilter | null;
  readonly createdAt?: DateTimeNullableFilter | null;
};

export type ImageStoreOrderByInput = {
  readonly id?: OrderDirection | null;
  readonly altText?: OrderDirection | null;
  readonly createdAt?: OrderDirection | null;
};

export type ImageStoreUpdateInput = {
  readonly image?: ImageFieldInput | null;
  readonly altText?: string | null;
  readonly createdAt?: DateTime | null;
};

export type ImageStoreUpdateArgs = {
  readonly where: ImageStoreWhereUniqueInput;
  readonly data: ImageStoreUpdateInput;
};

export type ImageStoreCreateInput = {
  readonly image?: ImageFieldInput | null;
  readonly altText?: string | null;
  readonly createdAt?: DateTime | null;
};

export type DescriptionOfApproval = {
  readonly __typename: "DescriptionOfApproval";
  readonly id: string;
  readonly slug: string | null;
  readonly url: string | null;
  readonly image: ImageStore | null;
  readonly noUI: boolean | null;
  readonly createdAt: DateTime | null;
};

export type DescriptionOfApprovalWhereUniqueInput = {
  readonly id?: string | null;
};

export type DescriptionOfApprovalWhereInput = {
  readonly AND?: TSGQLMaybeArray<DescriptionOfApprovalWhereInput> | null;
  readonly OR?: TSGQLMaybeArray<DescriptionOfApprovalWhereInput> | null;
  readonly NOT?: TSGQLMaybeArray<DescriptionOfApprovalWhereInput> | null;
  readonly id?: IDFilter | null;
  readonly slug?: StringFilter | null;
  readonly image?: ImageStoreWhereInput | null;
  readonly noUI?: BooleanFilter | null;
  readonly createdAt?: DateTimeNullableFilter | null;
};

export type DescriptionOfApprovalOrderByInput = {
  readonly id?: OrderDirection | null;
  readonly slug?: OrderDirection | null;
  readonly noUI?: OrderDirection | null;
  readonly createdAt?: OrderDirection | null;
};

export type DescriptionOfApprovalUpdateInput = {
  readonly slug?: string | null;
  readonly image?: ImageStoreRelateToOneForUpdateInput | null;
  readonly noUI?: boolean | null;
  readonly createdAt?: DateTime | null;
};

export type ImageStoreRelateToOneForUpdateInput = {
  readonly create?: ImageStoreCreateInput | null;
  readonly connect?: ImageStoreWhereUniqueInput | null;
  readonly disconnect?: boolean | null;
};

export type DescriptionOfApprovalUpdateArgs = {
  readonly where: DescriptionOfApprovalWhereUniqueInput;
  readonly data: DescriptionOfApprovalUpdateInput;
};

export type DescriptionOfApprovalCreateInput = {
  readonly slug?: string | null;
  readonly image?: ImageStoreRelateToOneForCreateInput | null;
  readonly noUI?: boolean | null;
  readonly createdAt?: DateTime | null;
};

export type ImageStoreRelateToOneForCreateInput = {
  readonly create?: ImageStoreCreateInput | null;
  readonly connect?: ImageStoreWhereUniqueInput | null;
};

export type Constractor = {
  readonly __typename: "Constractor";
  readonly id: string;
  readonly name: string | null;
  readonly type: string | null;
  readonly contracts: ReadonlyArray<Contract> | null;
  readonly contractsCount: number | null;
};

export type ConstractorcontractsArgs = {
  readonly where?: ContractWhereInput;
  readonly orderBy?: TSGQLMaybeArray<ContractOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: ContractWhereUniqueInput | null;
};

export type ConstractorcontractsCountArgs = {
  readonly where?: ContractWhereInput;
};

export type ConstractorWhereUniqueInput = {
  readonly id?: string | null;
};

export type ConstractorWhereInput = {
  readonly AND?: TSGQLMaybeArray<ConstractorWhereInput> | null;
  readonly OR?: TSGQLMaybeArray<ConstractorWhereInput> | null;
  readonly NOT?: TSGQLMaybeArray<ConstractorWhereInput> | null;
  readonly id?: IDFilter | null;
  readonly name?: StringFilter | null;
  readonly type?: StringNullableFilter | null;
  readonly contracts?: ContractManyRelationFilter | null;
};

export type ContractManyRelationFilter = {
  readonly every?: ContractWhereInput | null;
  readonly some?: ContractWhereInput | null;
  readonly none?: ContractWhereInput | null;
};

export type ConstractorOrderByInput = {
  readonly id?: OrderDirection | null;
  readonly name?: OrderDirection | null;
  readonly type?: OrderDirection | null;
};

export type ConstractorUpdateInput = {
  readonly name?: string | null;
  readonly type?: string | null;
  readonly contracts?: ContractRelateToManyForUpdateInput | null;
};

export type ContractRelateToManyForUpdateInput = {
  readonly disconnect?: TSGQLMaybeArray<ContractWhereUniqueInput> | null;
  readonly set?: TSGQLMaybeArray<ContractWhereUniqueInput> | null;
  readonly create?: TSGQLMaybeArray<ContractCreateInput> | null;
  readonly connect?: TSGQLMaybeArray<ContractWhereUniqueInput> | null;
};

export type ConstractorUpdateArgs = {
  readonly where: ConstractorWhereUniqueInput;
  readonly data: ConstractorUpdateInput;
};

export type ConstractorCreateInput = {
  readonly name?: string | null;
  readonly type?: string | null;
  readonly contracts?: ContractRelateToManyForCreateInput | null;
};

export type ContractRelateToManyForCreateInput = {
  readonly create?: TSGQLMaybeArray<ContractCreateInput> | null;
  readonly connect?: TSGQLMaybeArray<ContractWhereUniqueInput> | null;
};

export type FileStore = {
  readonly __typename: "FileStore";
  readonly id: string;
  readonly title: string | null;
  readonly file: FileFieldOutput | null;
  readonly createdAt: DateTime | null;
  readonly createdBy: User | null;
};

export type FileFieldOutput = {
  readonly __typename: "FileFieldOutput";
  readonly filename: string;
  readonly filesize: number;
  readonly url: string;
};

export type FileStoreWhereUniqueInput = {
  readonly id?: string | null;
};

export type FileStoreWhereInput = {
  readonly AND?: TSGQLMaybeArray<FileStoreWhereInput> | null;
  readonly OR?: TSGQLMaybeArray<FileStoreWhereInput> | null;
  readonly NOT?: TSGQLMaybeArray<FileStoreWhereInput> | null;
  readonly id?: IDFilter | null;
  readonly title?: StringFilter | null;
  readonly createdAt?: DateTimeNullableFilter | null;
  readonly createdBy?: UserWhereInput | null;
};

export type FileStoreOrderByInput = {
  readonly id?: OrderDirection | null;
  readonly title?: OrderDirection | null;
  readonly createdAt?: OrderDirection | null;
};

export type FileStoreUpdateInput = {
  readonly title?: string | null;
  readonly file?: FileFieldInput | null;
  readonly createdAt?: DateTime | null;
  readonly createdBy?: UserRelateToOneForUpdateInput | null;
};

export type FileFieldInput = {
  readonly upload: Upload;
};

export type FileStoreUpdateArgs = {
  readonly where: FileStoreWhereUniqueInput;
  readonly data: FileStoreUpdateInput;
};

export type FileStoreCreateInput = {
  readonly title?: string | null;
  readonly file?: FileFieldInput | null;
  readonly createdAt?: DateTime | null;
  readonly createdBy?: UserRelateToOneForCreateInput | null;
};

export type Contract = {
  readonly __typename: "Contract";
  readonly id: string;
  readonly title: string | null;
  readonly description: string | null;
  readonly startFrom: number | null;
  readonly end: number | null;
  readonly price: BigInt | null;
  readonly contractor: Constractor | null;
  readonly attachment: FileFieldOutput | null;
};

export type ContractWhereUniqueInput = {
  readonly id?: string | null;
};

export type ContractWhereInput = {
  readonly AND?: TSGQLMaybeArray<ContractWhereInput> | null;
  readonly OR?: TSGQLMaybeArray<ContractWhereInput> | null;
  readonly NOT?: TSGQLMaybeArray<ContractWhereInput> | null;
  readonly id?: IDFilter | null;
  readonly title?: StringFilter | null;
  readonly description?: StringFilter | null;
  readonly startFrom?: PairFilter | null;
  readonly end?: PairFilter | null;
  readonly price?: BigIntNullableFilter | null;
  readonly contractor?: ConstractorWhereInput | null;
};

export type ContractOrderByInput = {
  readonly id?: OrderDirection | null;
  readonly title?: OrderDirection | null;
  readonly description?: OrderDirection | null;
  readonly startFrom?: OrderDirection | null;
  readonly end?: OrderDirection | null;
  readonly price?: OrderDirection | null;
};

export type ContractUpdateInput = {
  readonly title?: string | null;
  readonly description?: string | null;
  readonly startFrom?: number | null;
  readonly end?: number | null;
  readonly price?: BigInt | null;
  readonly contractor?: ConstractorRelateToOneForUpdateInput | null;
  readonly attachment?: FileFieldInput | null;
};

export type ConstractorRelateToOneForUpdateInput = {
  readonly create?: ConstractorCreateInput | null;
  readonly connect?: ConstractorWhereUniqueInput | null;
  readonly disconnect?: boolean | null;
};

export type ContractUpdateArgs = {
  readonly where: ContractWhereUniqueInput;
  readonly data: ContractUpdateInput;
};

export type ContractCreateInput = {
  readonly title?: string | null;
  readonly description?: string | null;
  readonly startFrom?: number | null;
  readonly end?: number | null;
  readonly price?: BigInt | null;
  readonly contractor?: ConstractorRelateToOneForCreateInput | null;
  readonly attachment?: FileFieldInput | null;
};

export type ConstractorRelateToOneForCreateInput = {
  readonly create?: ConstractorCreateInput | null;
  readonly connect?: ConstractorWhereUniqueInput | null;
};

export type Design = {
  readonly __typename: "Design";
  readonly id: string;
  readonly title: string | null;
  readonly design: ReadonlyArray<FileStore> | null;
  readonly designCount: number | null;
  readonly download: JSON | null;
  readonly category: ReadonlyArray<Category> | null;
  readonly categoryCount: number | null;
  readonly createdAt: DateTime | null;
  readonly createdBy: User | null;
};

export type DesigndesignArgs = {
  readonly where?: FileStoreWhereInput;
  readonly orderBy?: TSGQLMaybeArray<FileStoreOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: FileStoreWhereUniqueInput | null;
};

export type DesigndesignCountArgs = {
  readonly where?: FileStoreWhereInput;
};

export type DesigncategoryArgs = {
  readonly where?: CategoryWhereInput;
  readonly orderBy?: TSGQLMaybeArray<CategoryOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: CategoryWhereUniqueInput | null;
};

export type DesigncategoryCountArgs = {
  readonly where?: CategoryWhereInput;
};

export type DesignWhereUniqueInput = {
  readonly id?: string | null;
};

export type DesignWhereInput = {
  readonly AND?: TSGQLMaybeArray<DesignWhereInput> | null;
  readonly OR?: TSGQLMaybeArray<DesignWhereInput> | null;
  readonly NOT?: TSGQLMaybeArray<DesignWhereInput> | null;
  readonly id?: IDFilter | null;
  readonly title?: StringFilter | null;
  readonly design?: FileStoreManyRelationFilter | null;
  readonly category?: CategoryManyRelationFilter | null;
  readonly createdAt?: DateTimeNullableFilter | null;
  readonly createdBy?: UserWhereInput | null;
};

export type FileStoreManyRelationFilter = {
  readonly every?: FileStoreWhereInput | null;
  readonly some?: FileStoreWhereInput | null;
  readonly none?: FileStoreWhereInput | null;
};

export type CategoryManyRelationFilter = {
  readonly every?: CategoryWhereInput | null;
  readonly some?: CategoryWhereInput | null;
  readonly none?: CategoryWhereInput | null;
};

export type DesignOrderByInput = {
  readonly id?: OrderDirection | null;
  readonly title?: OrderDirection | null;
  readonly createdAt?: OrderDirection | null;
};

export type DesignUpdateInput = {
  readonly title?: string | null;
  readonly design?: FileStoreRelateToManyForUpdateInput | null;
  readonly category?: CategoryRelateToManyForUpdateInput | null;
  readonly createdAt?: DateTime | null;
  readonly createdBy?: UserRelateToOneForUpdateInput | null;
};

export type FileStoreRelateToManyForUpdateInput = {
  readonly disconnect?: TSGQLMaybeArray<FileStoreWhereUniqueInput> | null;
  readonly set?: TSGQLMaybeArray<FileStoreWhereUniqueInput> | null;
  readonly create?: TSGQLMaybeArray<FileStoreCreateInput> | null;
  readonly connect?: TSGQLMaybeArray<FileStoreWhereUniqueInput> | null;
};

export type CategoryRelateToManyForUpdateInput = {
  readonly disconnect?: TSGQLMaybeArray<CategoryWhereUniqueInput> | null;
  readonly set?: TSGQLMaybeArray<CategoryWhereUniqueInput> | null;
  readonly create?: TSGQLMaybeArray<CategoryCreateInput> | null;
  readonly connect?: TSGQLMaybeArray<CategoryWhereUniqueInput> | null;
};

export type DesignUpdateArgs = {
  readonly where: DesignWhereUniqueInput;
  readonly data: DesignUpdateInput;
};

export type DesignCreateInput = {
  readonly title?: string | null;
  readonly design?: FileStoreRelateToManyForCreateInput | null;
  readonly category?: CategoryRelateToManyForCreateInput | null;
  readonly createdAt?: DateTime | null;
  readonly createdBy?: UserRelateToOneForCreateInput | null;
};

export type FileStoreRelateToManyForCreateInput = {
  readonly create?: TSGQLMaybeArray<FileStoreCreateInput> | null;
  readonly connect?: TSGQLMaybeArray<FileStoreWhereUniqueInput> | null;
};

export type CategoryRelateToManyForCreateInput = {
  readonly create?: TSGQLMaybeArray<CategoryCreateInput> | null;
  readonly connect?: TSGQLMaybeArray<CategoryWhereUniqueInput> | null;
};

export type DailyReport = {
  readonly __typename: "DailyReport";
  readonly id: string;
  readonly document: FileFieldOutput | null;
  readonly createdBy: User | null;
  readonly date: DateTime | null;
};

export type DailyReportWhereUniqueInput = {
  readonly id?: string | null;
};

export type DailyReportWhereInput = {
  readonly AND?: TSGQLMaybeArray<DailyReportWhereInput> | null;
  readonly OR?: TSGQLMaybeArray<DailyReportWhereInput> | null;
  readonly NOT?: TSGQLMaybeArray<DailyReportWhereInput> | null;
  readonly id?: IDFilter | null;
  readonly createdBy?: UserWhereInput | null;
  readonly date?: DateTimeNullableFilter | null;
};

export type DailyReportOrderByInput = {
  readonly id?: OrderDirection | null;
  readonly date?: OrderDirection | null;
};

export type DailyReportUpdateInput = {
  readonly document?: FileFieldInput | null;
  readonly createdBy?: UserRelateToOneForUpdateInput | null;
  readonly date?: DateTime | null;
};

export type DailyReportUpdateArgs = {
  readonly where: DailyReportWhereUniqueInput;
  readonly data: DailyReportUpdateInput;
};

export type DailyReportCreateInput = {
  readonly document?: FileFieldInput | null;
  readonly createdBy?: UserRelateToOneForCreateInput | null;
  readonly date?: DateTime | null;
};

export type User = {
  readonly __typename: "User";
  readonly id: string;
  readonly name: string | null;
  readonly email: string | null;
  readonly role: string | null;
  readonly password: PasswordState | null;
  readonly statements: ReadonlyArray<Statement> | null;
  readonly statementsCount: number | null;
  readonly approvals: ReadonlyArray<Approval> | null;
  readonly approvalsCount: number | null;
  readonly descriptions: ReadonlyArray<Description> | null;
  readonly descriptionsCount: number | null;
  readonly Designs: ReadonlyArray<Design> | null;
  readonly DesignsCount: number | null;
  readonly dailyReports: ReadonlyArray<DailyReport> | null;
  readonly dailyReportsCount: number | null;
  readonly createdAt: DateTime | null;
};

export type UserstatementsArgs = {
  readonly where?: StatementWhereInput;
  readonly orderBy?: TSGQLMaybeArray<StatementOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: StatementWhereUniqueInput | null;
};

export type UserstatementsCountArgs = {
  readonly where?: StatementWhereInput;
};

export type UserapprovalsArgs = {
  readonly where?: ApprovalWhereInput;
  readonly orderBy?: TSGQLMaybeArray<ApprovalOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: ApprovalWhereUniqueInput | null;
};

export type UserapprovalsCountArgs = {
  readonly where?: ApprovalWhereInput;
};

export type UserdescriptionsArgs = {
  readonly where?: DescriptionWhereInput;
  readonly orderBy?: TSGQLMaybeArray<DescriptionOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: DescriptionWhereUniqueInput | null;
};

export type UserdescriptionsCountArgs = {
  readonly where?: DescriptionWhereInput;
};

export type UserDesignsArgs = {
  readonly where?: DesignWhereInput;
  readonly orderBy?: TSGQLMaybeArray<DesignOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: DesignWhereUniqueInput | null;
};

export type UserDesignsCountArgs = {
  readonly where?: DesignWhereInput;
};

export type UserdailyReportsArgs = {
  readonly where?: DailyReportWhereInput;
  readonly orderBy?: TSGQLMaybeArray<DailyReportOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: DailyReportWhereUniqueInput | null;
};

export type UserdailyReportsCountArgs = {
  readonly where?: DailyReportWhereInput;
};

export type PasswordState = {
  readonly __typename: "PasswordState";
  readonly isSet: boolean;
};

export type UserWhereUniqueInput = {
  readonly id?: string | null;
  readonly email?: string | null;
};

export type UserWhereInput = {
  readonly AND?: TSGQLMaybeArray<UserWhereInput> | null;
  readonly OR?: TSGQLMaybeArray<UserWhereInput> | null;
  readonly NOT?: TSGQLMaybeArray<UserWhereInput> | null;
  readonly id?: IDFilter | null;
  readonly name?: StringFilter | null;
  readonly email?: StringFilter | null;
  readonly role?: StringNullableFilter | null;
  readonly statements?: StatementManyRelationFilter | null;
  readonly approvals?: ApprovalManyRelationFilter | null;
  readonly descriptions?: DescriptionManyRelationFilter | null;
  readonly Designs?: DesignManyRelationFilter | null;
  readonly dailyReports?: DailyReportManyRelationFilter | null;
  readonly createdAt?: DateTimeNullableFilter | null;
};

export type ApprovalManyRelationFilter = {
  readonly every?: ApprovalWhereInput | null;
  readonly some?: ApprovalWhereInput | null;
  readonly none?: ApprovalWhereInput | null;
};

export type DesignManyRelationFilter = {
  readonly every?: DesignWhereInput | null;
  readonly some?: DesignWhereInput | null;
  readonly none?: DesignWhereInput | null;
};

export type DailyReportManyRelationFilter = {
  readonly every?: DailyReportWhereInput | null;
  readonly some?: DailyReportWhereInput | null;
  readonly none?: DailyReportWhereInput | null;
};

export type UserOrderByInput = {
  readonly id?: OrderDirection | null;
  readonly name?: OrderDirection | null;
  readonly email?: OrderDirection | null;
  readonly role?: OrderDirection | null;
  readonly createdAt?: OrderDirection | null;
};

export type UserUpdateInput = {
  readonly name?: string | null;
  readonly email?: string | null;
  readonly role?: string | null;
  readonly password?: string | null;
  readonly statements?: StatementRelateToManyForUpdateInput | null;
  readonly approvals?: ApprovalRelateToManyForUpdateInput | null;
  readonly descriptions?: DescriptionRelateToManyForUpdateInput | null;
  readonly Designs?: DesignRelateToManyForUpdateInput | null;
  readonly dailyReports?: DailyReportRelateToManyForUpdateInput | null;
  readonly createdAt?: DateTime | null;
};

export type ApprovalRelateToManyForUpdateInput = {
  readonly disconnect?: TSGQLMaybeArray<ApprovalWhereUniqueInput> | null;
  readonly set?: TSGQLMaybeArray<ApprovalWhereUniqueInput> | null;
  readonly create?: TSGQLMaybeArray<ApprovalCreateInput> | null;
  readonly connect?: TSGQLMaybeArray<ApprovalWhereUniqueInput> | null;
};

export type DesignRelateToManyForUpdateInput = {
  readonly disconnect?: TSGQLMaybeArray<DesignWhereUniqueInput> | null;
  readonly set?: TSGQLMaybeArray<DesignWhereUniqueInput> | null;
  readonly create?: TSGQLMaybeArray<DesignCreateInput> | null;
  readonly connect?: TSGQLMaybeArray<DesignWhereUniqueInput> | null;
};

export type DailyReportRelateToManyForUpdateInput = {
  readonly disconnect?: TSGQLMaybeArray<DailyReportWhereUniqueInput> | null;
  readonly set?: TSGQLMaybeArray<DailyReportWhereUniqueInput> | null;
  readonly create?: TSGQLMaybeArray<DailyReportCreateInput> | null;
  readonly connect?: TSGQLMaybeArray<DailyReportWhereUniqueInput> | null;
};

export type UserUpdateArgs = {
  readonly where: UserWhereUniqueInput;
  readonly data: UserUpdateInput;
};

export type UserCreateInput = {
  readonly name?: string | null;
  readonly email?: string | null;
  readonly role?: string | null;
  readonly password?: string | null;
  readonly statements?: StatementRelateToManyForCreateInput | null;
  readonly approvals?: ApprovalRelateToManyForCreateInput | null;
  readonly descriptions?: DescriptionRelateToManyForCreateInput | null;
  readonly Designs?: DesignRelateToManyForCreateInput | null;
  readonly dailyReports?: DailyReportRelateToManyForCreateInput | null;
  readonly createdAt?: DateTime | null;
};

export type ApprovalRelateToManyForCreateInput = {
  readonly create?: TSGQLMaybeArray<ApprovalCreateInput> | null;
  readonly connect?: TSGQLMaybeArray<ApprovalWhereUniqueInput> | null;
};

export type DesignRelateToManyForCreateInput = {
  readonly create?: TSGQLMaybeArray<DesignCreateInput> | null;
  readonly connect?: TSGQLMaybeArray<DesignWhereUniqueInput> | null;
};

export type DailyReportRelateToManyForCreateInput = {
  readonly create?: TSGQLMaybeArray<DailyReportCreateInput> | null;
  readonly connect?: TSGQLMaybeArray<DailyReportWhereUniqueInput> | null;
};

export type Category = {
  readonly __typename: "Category";
  readonly id: string;
  readonly title: string | null;
  readonly description: string | null;
  readonly children: ReadonlyArray<Category> | null;
  readonly childrenCount: number | null;
  readonly parent: Category | null;
};

export type CategorychildrenArgs = {
  readonly where?: CategoryWhereInput;
  readonly orderBy?: TSGQLMaybeArray<CategoryOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: CategoryWhereUniqueInput | null;
};

export type CategorychildrenCountArgs = {
  readonly where?: CategoryWhereInput;
};

export type CategoryWhereUniqueInput = {
  readonly id?: string | null;
};

export type CategoryWhereInput = {
  readonly AND?: TSGQLMaybeArray<CategoryWhereInput> | null;
  readonly OR?: TSGQLMaybeArray<CategoryWhereInput> | null;
  readonly NOT?: TSGQLMaybeArray<CategoryWhereInput> | null;
  readonly id?: IDFilter | null;
  readonly title?: StringFilter | null;
  readonly description?: StringFilter | null;
  readonly children?: CategoryManyRelationFilter | null;
  readonly parent?: CategoryWhereInput | null;
};

export type CategoryOrderByInput = {
  readonly id?: OrderDirection | null;
  readonly title?: OrderDirection | null;
  readonly description?: OrderDirection | null;
};

export type CategoryUpdateInput = {
  readonly title?: string | null;
  readonly description?: string | null;
  readonly children?: CategoryRelateToManyForUpdateInput | null;
  readonly parent?: CategoryRelateToOneForUpdateInput | null;
};

export type CategoryRelateToOneForUpdateInput = {
  readonly create?: CategoryCreateInput | null;
  readonly connect?: CategoryWhereUniqueInput | null;
  readonly disconnect?: boolean | null;
};

export type CategoryUpdateArgs = {
  readonly where: CategoryWhereUniqueInput;
  readonly data: CategoryUpdateInput;
};

export type CategoryCreateInput = {
  readonly title?: string | null;
  readonly description?: string | null;
  readonly children?: CategoryRelateToManyForCreateInput | null;
  readonly parent?: CategoryRelateToOneForCreateInput | null;
};

export type CategoryRelateToOneForCreateInput = {
  readonly create?: CategoryCreateInput | null;
  readonly connect?: CategoryWhereUniqueInput | null;
};

export type Log = {
  readonly __typename: "Log";
  readonly id: string;
  readonly type: string | null;
  readonly action: string | null;
  readonly message: string | null;
  readonly date: DateTime | null;
};

export type LogWhereUniqueInput = {
  readonly id?: string | null;
};

export type LogWhereInput = {
  readonly AND?: TSGQLMaybeArray<LogWhereInput> | null;
  readonly OR?: TSGQLMaybeArray<LogWhereInput> | null;
  readonly NOT?: TSGQLMaybeArray<LogWhereInput> | null;
  readonly id?: IDFilter | null;
  readonly type?: StringNullableFilter | null;
  readonly action?: StringNullableFilter | null;
  readonly message?: StringFilter | null;
  readonly date?: DateTimeNullableFilter | null;
};

export type LogOrderByInput = {
  readonly id?: OrderDirection | null;
  readonly type?: OrderDirection | null;
  readonly action?: OrderDirection | null;
  readonly message?: OrderDirection | null;
  readonly date?: OrderDirection | null;
};

export type LogUpdateInput = {
  readonly type?: string | null;
  readonly action?: string | null;
  readonly message?: string | null;
  readonly date?: DateTime | null;
};

export type LogUpdateArgs = {
  readonly where: LogWhereUniqueInput;
  readonly data: LogUpdateInput;
};

export type LogCreateInput = {
  readonly type?: string | null;
  readonly action?: string | null;
  readonly message?: string | null;
  readonly date?: DateTime | null;
};

export type Tag = {
  readonly __typename: "Tag";
  readonly id: string;
  readonly name: string | null;
};

export type TagWhereUniqueInput = {
  readonly id?: string | null;
};

export type TagWhereInput = {
  readonly AND?: TSGQLMaybeArray<TagWhereInput> | null;
  readonly OR?: TSGQLMaybeArray<TagWhereInput> | null;
  readonly NOT?: TSGQLMaybeArray<TagWhereInput> | null;
  readonly id?: IDFilter | null;
  readonly name?: StringFilter | null;
};

export type TagOrderByInput = {
  readonly id?: OrderDirection | null;
  readonly name?: OrderDirection | null;
};

export type TagUpdateInput = {
  readonly name?: string | null;
};

export type TagUpdateArgs = {
  readonly where: TagWhereUniqueInput;
  readonly data: TagUpdateInput;
};

export type TagCreateInput = {
  readonly name?: string | null;
};

export type JSON = any;

export type Mutation = {
  readonly __typename: "Mutation";
  readonly createApproval: Approval | null;
  readonly createApprovals: ReadonlyArray<Approval | null> | null;
  readonly updateApproval: Approval | null;
  readonly updateApprovals: ReadonlyArray<Approval | null> | null;
  readonly deleteApproval: Approval | null;
  readonly deleteApprovals: ReadonlyArray<Approval | null> | null;
  readonly createDescription: Description | null;
  readonly createDescriptions: ReadonlyArray<Description | null> | null;
  readonly updateDescription: Description | null;
  readonly updateDescriptions: ReadonlyArray<Description | null> | null;
  readonly deleteDescription: Description | null;
  readonly deleteDescriptions: ReadonlyArray<Description | null> | null;
  readonly createStatement: Statement | null;
  readonly createStatements: ReadonlyArray<Statement | null> | null;
  readonly updateStatement: Statement | null;
  readonly updateStatements: ReadonlyArray<Statement | null> | null;
  readonly deleteStatement: Statement | null;
  readonly deleteStatements: ReadonlyArray<Statement | null> | null;
  readonly createStatementItem: StatementItem | null;
  readonly createStatementItems: ReadonlyArray<StatementItem | null> | null;
  readonly updateStatementItem: StatementItem | null;
  readonly updateStatementItems: ReadonlyArray<StatementItem | null> | null;
  readonly deleteStatementItem: StatementItem | null;
  readonly deleteStatementItems: ReadonlyArray<StatementItem | null> | null;
  readonly createPayment: Payment | null;
  readonly createPayments: ReadonlyArray<Payment | null> | null;
  readonly updatePayment: Payment | null;
  readonly updatePayments: ReadonlyArray<Payment | null> | null;
  readonly deletePayment: Payment | null;
  readonly deletePayments: ReadonlyArray<Payment | null> | null;
  readonly createImageStore: ImageStore | null;
  readonly createImageStores: ReadonlyArray<ImageStore | null> | null;
  readonly updateImageStore: ImageStore | null;
  readonly updateImageStores: ReadonlyArray<ImageStore | null> | null;
  readonly deleteImageStore: ImageStore | null;
  readonly deleteImageStores: ReadonlyArray<ImageStore | null> | null;
  readonly createDescriptionOfApproval: DescriptionOfApproval | null;
  readonly createDescriptionOfApprovals: ReadonlyArray<DescriptionOfApproval | null> | null;
  readonly updateDescriptionOfApproval: DescriptionOfApproval | null;
  readonly updateDescriptionOfApprovals: ReadonlyArray<DescriptionOfApproval | null> | null;
  readonly deleteDescriptionOfApproval: DescriptionOfApproval | null;
  readonly deleteDescriptionOfApprovals: ReadonlyArray<DescriptionOfApproval | null> | null;
  readonly createConstractor: Constractor | null;
  readonly createConstractors: ReadonlyArray<Constractor | null> | null;
  readonly updateConstractor: Constractor | null;
  readonly updateConstractors: ReadonlyArray<Constractor | null> | null;
  readonly deleteConstractor: Constractor | null;
  readonly deleteConstractors: ReadonlyArray<Constractor | null> | null;
  readonly createFileStore: FileStore | null;
  readonly createFileStores: ReadonlyArray<FileStore | null> | null;
  readonly updateFileStore: FileStore | null;
  readonly updateFileStores: ReadonlyArray<FileStore | null> | null;
  readonly deleteFileStore: FileStore | null;
  readonly deleteFileStores: ReadonlyArray<FileStore | null> | null;
  readonly createContract: Contract | null;
  readonly createContracts: ReadonlyArray<Contract | null> | null;
  readonly updateContract: Contract | null;
  readonly updateContracts: ReadonlyArray<Contract | null> | null;
  readonly deleteContract: Contract | null;
  readonly deleteContracts: ReadonlyArray<Contract | null> | null;
  readonly createDesign: Design | null;
  readonly createDesigns: ReadonlyArray<Design | null> | null;
  readonly updateDesign: Design | null;
  readonly updateDesigns: ReadonlyArray<Design | null> | null;
  readonly deleteDesign: Design | null;
  readonly deleteDesigns: ReadonlyArray<Design | null> | null;
  readonly createDailyReport: DailyReport | null;
  readonly createDailyReports: ReadonlyArray<DailyReport | null> | null;
  readonly updateDailyReport: DailyReport | null;
  readonly updateDailyReports: ReadonlyArray<DailyReport | null> | null;
  readonly deleteDailyReport: DailyReport | null;
  readonly deleteDailyReports: ReadonlyArray<DailyReport | null> | null;
  readonly createUser: User | null;
  readonly createUsers: ReadonlyArray<User | null> | null;
  readonly updateUser: User | null;
  readonly updateUsers: ReadonlyArray<User | null> | null;
  readonly deleteUser: User | null;
  readonly deleteUsers: ReadonlyArray<User | null> | null;
  readonly createCategory: Category | null;
  readonly createCategories: ReadonlyArray<Category | null> | null;
  readonly updateCategory: Category | null;
  readonly updateCategories: ReadonlyArray<Category | null> | null;
  readonly deleteCategory: Category | null;
  readonly deleteCategories: ReadonlyArray<Category | null> | null;
  readonly createLog: Log | null;
  readonly createLogs: ReadonlyArray<Log | null> | null;
  readonly updateLog: Log | null;
  readonly updateLogs: ReadonlyArray<Log | null> | null;
  readonly deleteLog: Log | null;
  readonly deleteLogs: ReadonlyArray<Log | null> | null;
  readonly createTag: Tag | null;
  readonly createTags: ReadonlyArray<Tag | null> | null;
  readonly updateTag: Tag | null;
  readonly updateTags: ReadonlyArray<Tag | null> | null;
  readonly deleteTag: Tag | null;
  readonly deleteTags: ReadonlyArray<Tag | null> | null;
  readonly endSession: boolean;
  readonly authenticateUserWithPassword: UserAuthenticationWithPasswordResult | null;
  readonly createInitialUser: UserAuthenticationWithPasswordSuccess;
};

export type MutationcreateApprovalArgs = {
  readonly data: ApprovalCreateInput;
};

export type MutationcreateApprovalsArgs = {
  readonly data: TSGQLMaybeArray<ApprovalCreateInput>;
};

export type MutationupdateApprovalArgs = {
  readonly where: ApprovalWhereUniqueInput;
  readonly data: ApprovalUpdateInput;
};

export type MutationupdateApprovalsArgs = {
  readonly data: TSGQLMaybeArray<ApprovalUpdateArgs>;
};

export type MutationdeleteApprovalArgs = {
  readonly where: ApprovalWhereUniqueInput;
};

export type MutationdeleteApprovalsArgs = {
  readonly where: TSGQLMaybeArray<ApprovalWhereUniqueInput>;
};

export type MutationcreateDescriptionArgs = {
  readonly data: DescriptionCreateInput;
};

export type MutationcreateDescriptionsArgs = {
  readonly data: TSGQLMaybeArray<DescriptionCreateInput>;
};

export type MutationupdateDescriptionArgs = {
  readonly where: DescriptionWhereUniqueInput;
  readonly data: DescriptionUpdateInput;
};

export type MutationupdateDescriptionsArgs = {
  readonly data: TSGQLMaybeArray<DescriptionUpdateArgs>;
};

export type MutationdeleteDescriptionArgs = {
  readonly where: DescriptionWhereUniqueInput;
};

export type MutationdeleteDescriptionsArgs = {
  readonly where: TSGQLMaybeArray<DescriptionWhereUniqueInput>;
};

export type MutationcreateStatementArgs = {
  readonly data: StatementCreateInput;
};

export type MutationcreateStatementsArgs = {
  readonly data: TSGQLMaybeArray<StatementCreateInput>;
};

export type MutationupdateStatementArgs = {
  readonly where: StatementWhereUniqueInput;
  readonly data: StatementUpdateInput;
};

export type MutationupdateStatementsArgs = {
  readonly data: TSGQLMaybeArray<StatementUpdateArgs>;
};

export type MutationdeleteStatementArgs = {
  readonly where: StatementWhereUniqueInput;
};

export type MutationdeleteStatementsArgs = {
  readonly where: TSGQLMaybeArray<StatementWhereUniqueInput>;
};

export type MutationcreateStatementItemArgs = {
  readonly data: StatementItemCreateInput;
};

export type MutationcreateStatementItemsArgs = {
  readonly data: TSGQLMaybeArray<StatementItemCreateInput>;
};

export type MutationupdateStatementItemArgs = {
  readonly where: StatementItemWhereUniqueInput;
  readonly data: StatementItemUpdateInput;
};

export type MutationupdateStatementItemsArgs = {
  readonly data: TSGQLMaybeArray<StatementItemUpdateArgs>;
};

export type MutationdeleteStatementItemArgs = {
  readonly where: StatementItemWhereUniqueInput;
};

export type MutationdeleteStatementItemsArgs = {
  readonly where: TSGQLMaybeArray<StatementItemWhereUniqueInput>;
};

export type MutationcreatePaymentArgs = {
  readonly data: PaymentCreateInput;
};

export type MutationcreatePaymentsArgs = {
  readonly data: TSGQLMaybeArray<PaymentCreateInput>;
};

export type MutationupdatePaymentArgs = {
  readonly where: PaymentWhereUniqueInput;
  readonly data: PaymentUpdateInput;
};

export type MutationupdatePaymentsArgs = {
  readonly data: TSGQLMaybeArray<PaymentUpdateArgs>;
};

export type MutationdeletePaymentArgs = {
  readonly where: PaymentWhereUniqueInput;
};

export type MutationdeletePaymentsArgs = {
  readonly where: TSGQLMaybeArray<PaymentWhereUniqueInput>;
};

export type MutationcreateImageStoreArgs = {
  readonly data: ImageStoreCreateInput;
};

export type MutationcreateImageStoresArgs = {
  readonly data: TSGQLMaybeArray<ImageStoreCreateInput>;
};

export type MutationupdateImageStoreArgs = {
  readonly where: ImageStoreWhereUniqueInput;
  readonly data: ImageStoreUpdateInput;
};

export type MutationupdateImageStoresArgs = {
  readonly data: TSGQLMaybeArray<ImageStoreUpdateArgs>;
};

export type MutationdeleteImageStoreArgs = {
  readonly where: ImageStoreWhereUniqueInput;
};

export type MutationdeleteImageStoresArgs = {
  readonly where: TSGQLMaybeArray<ImageStoreWhereUniqueInput>;
};

export type MutationcreateDescriptionOfApprovalArgs = {
  readonly data: DescriptionOfApprovalCreateInput;
};

export type MutationcreateDescriptionOfApprovalsArgs = {
  readonly data: TSGQLMaybeArray<DescriptionOfApprovalCreateInput>;
};

export type MutationupdateDescriptionOfApprovalArgs = {
  readonly where: DescriptionOfApprovalWhereUniqueInput;
  readonly data: DescriptionOfApprovalUpdateInput;
};

export type MutationupdateDescriptionOfApprovalsArgs = {
  readonly data: TSGQLMaybeArray<DescriptionOfApprovalUpdateArgs>;
};

export type MutationdeleteDescriptionOfApprovalArgs = {
  readonly where: DescriptionOfApprovalWhereUniqueInput;
};

export type MutationdeleteDescriptionOfApprovalsArgs = {
  readonly where: TSGQLMaybeArray<DescriptionOfApprovalWhereUniqueInput>;
};

export type MutationcreateConstractorArgs = {
  readonly data: ConstractorCreateInput;
};

export type MutationcreateConstractorsArgs = {
  readonly data: TSGQLMaybeArray<ConstractorCreateInput>;
};

export type MutationupdateConstractorArgs = {
  readonly where: ConstractorWhereUniqueInput;
  readonly data: ConstractorUpdateInput;
};

export type MutationupdateConstractorsArgs = {
  readonly data: TSGQLMaybeArray<ConstractorUpdateArgs>;
};

export type MutationdeleteConstractorArgs = {
  readonly where: ConstractorWhereUniqueInput;
};

export type MutationdeleteConstractorsArgs = {
  readonly where: TSGQLMaybeArray<ConstractorWhereUniqueInput>;
};

export type MutationcreateFileStoreArgs = {
  readonly data: FileStoreCreateInput;
};

export type MutationcreateFileStoresArgs = {
  readonly data: TSGQLMaybeArray<FileStoreCreateInput>;
};

export type MutationupdateFileStoreArgs = {
  readonly where: FileStoreWhereUniqueInput;
  readonly data: FileStoreUpdateInput;
};

export type MutationupdateFileStoresArgs = {
  readonly data: TSGQLMaybeArray<FileStoreUpdateArgs>;
};

export type MutationdeleteFileStoreArgs = {
  readonly where: FileStoreWhereUniqueInput;
};

export type MutationdeleteFileStoresArgs = {
  readonly where: TSGQLMaybeArray<FileStoreWhereUniqueInput>;
};

export type MutationcreateContractArgs = {
  readonly data: ContractCreateInput;
};

export type MutationcreateContractsArgs = {
  readonly data: TSGQLMaybeArray<ContractCreateInput>;
};

export type MutationupdateContractArgs = {
  readonly where: ContractWhereUniqueInput;
  readonly data: ContractUpdateInput;
};

export type MutationupdateContractsArgs = {
  readonly data: TSGQLMaybeArray<ContractUpdateArgs>;
};

export type MutationdeleteContractArgs = {
  readonly where: ContractWhereUniqueInput;
};

export type MutationdeleteContractsArgs = {
  readonly where: TSGQLMaybeArray<ContractWhereUniqueInput>;
};

export type MutationcreateDesignArgs = {
  readonly data: DesignCreateInput;
};

export type MutationcreateDesignsArgs = {
  readonly data: TSGQLMaybeArray<DesignCreateInput>;
};

export type MutationupdateDesignArgs = {
  readonly where: DesignWhereUniqueInput;
  readonly data: DesignUpdateInput;
};

export type MutationupdateDesignsArgs = {
  readonly data: TSGQLMaybeArray<DesignUpdateArgs>;
};

export type MutationdeleteDesignArgs = {
  readonly where: DesignWhereUniqueInput;
};

export type MutationdeleteDesignsArgs = {
  readonly where: TSGQLMaybeArray<DesignWhereUniqueInput>;
};

export type MutationcreateDailyReportArgs = {
  readonly data: DailyReportCreateInput;
};

export type MutationcreateDailyReportsArgs = {
  readonly data: TSGQLMaybeArray<DailyReportCreateInput>;
};

export type MutationupdateDailyReportArgs = {
  readonly where: DailyReportWhereUniqueInput;
  readonly data: DailyReportUpdateInput;
};

export type MutationupdateDailyReportsArgs = {
  readonly data: TSGQLMaybeArray<DailyReportUpdateArgs>;
};

export type MutationdeleteDailyReportArgs = {
  readonly where: DailyReportWhereUniqueInput;
};

export type MutationdeleteDailyReportsArgs = {
  readonly where: TSGQLMaybeArray<DailyReportWhereUniqueInput>;
};

export type MutationcreateUserArgs = {
  readonly data: UserCreateInput;
};

export type MutationcreateUsersArgs = {
  readonly data: TSGQLMaybeArray<UserCreateInput>;
};

export type MutationupdateUserArgs = {
  readonly where: UserWhereUniqueInput;
  readonly data: UserUpdateInput;
};

export type MutationupdateUsersArgs = {
  readonly data: TSGQLMaybeArray<UserUpdateArgs>;
};

export type MutationdeleteUserArgs = {
  readonly where: UserWhereUniqueInput;
};

export type MutationdeleteUsersArgs = {
  readonly where: TSGQLMaybeArray<UserWhereUniqueInput>;
};

export type MutationcreateCategoryArgs = {
  readonly data: CategoryCreateInput;
};

export type MutationcreateCategoriesArgs = {
  readonly data: TSGQLMaybeArray<CategoryCreateInput>;
};

export type MutationupdateCategoryArgs = {
  readonly where: CategoryWhereUniqueInput;
  readonly data: CategoryUpdateInput;
};

export type MutationupdateCategoriesArgs = {
  readonly data: TSGQLMaybeArray<CategoryUpdateArgs>;
};

export type MutationdeleteCategoryArgs = {
  readonly where: CategoryWhereUniqueInput;
};

export type MutationdeleteCategoriesArgs = {
  readonly where: TSGQLMaybeArray<CategoryWhereUniqueInput>;
};

export type MutationcreateLogArgs = {
  readonly data: LogCreateInput;
};

export type MutationcreateLogsArgs = {
  readonly data: TSGQLMaybeArray<LogCreateInput>;
};

export type MutationupdateLogArgs = {
  readonly where: LogWhereUniqueInput;
  readonly data: LogUpdateInput;
};

export type MutationupdateLogsArgs = {
  readonly data: TSGQLMaybeArray<LogUpdateArgs>;
};

export type MutationdeleteLogArgs = {
  readonly where: LogWhereUniqueInput;
};

export type MutationdeleteLogsArgs = {
  readonly where: TSGQLMaybeArray<LogWhereUniqueInput>;
};

export type MutationcreateTagArgs = {
  readonly data: TagCreateInput;
};

export type MutationcreateTagsArgs = {
  readonly data: TSGQLMaybeArray<TagCreateInput>;
};

export type MutationupdateTagArgs = {
  readonly where: TagWhereUniqueInput;
  readonly data: TagUpdateInput;
};

export type MutationupdateTagsArgs = {
  readonly data: TSGQLMaybeArray<TagUpdateArgs>;
};

export type MutationdeleteTagArgs = {
  readonly where: TagWhereUniqueInput;
};

export type MutationdeleteTagsArgs = {
  readonly where: TSGQLMaybeArray<TagWhereUniqueInput>;
};

export type MutationauthenticateUserWithPasswordArgs = {
  readonly email: string;
  readonly password: string;
};

export type MutationcreateInitialUserArgs = {
  readonly data: CreateInitialUserInput;
};

export type UserAuthenticationWithPasswordResult = UserAuthenticationWithPasswordSuccess | UserAuthenticationWithPasswordFailure;

export type UserAuthenticationWithPasswordSuccess = {
  readonly __typename: "UserAuthenticationWithPasswordSuccess";
  readonly sessionToken: string;
  readonly item: User;
};

export type UserAuthenticationWithPasswordFailure = {
  readonly __typename: "UserAuthenticationWithPasswordFailure";
  readonly message: string;
};

export type CreateInitialUserInput = {
  readonly name?: string | null;
  readonly email?: string | null;
  readonly role?: string | null;
  readonly password?: string | null;
};

export type Query = {
  readonly __typename: "Query";
  readonly approvals: ReadonlyArray<Approval> | null;
  readonly approval: Approval | null;
  readonly approvalsCount: number | null;
  readonly descriptions: ReadonlyArray<Description> | null;
  readonly description: Description | null;
  readonly descriptionsCount: number | null;
  readonly statements: ReadonlyArray<Statement> | null;
  readonly statement: Statement | null;
  readonly statementsCount: number | null;
  readonly statementItems: ReadonlyArray<StatementItem> | null;
  readonly statementItem: StatementItem | null;
  readonly statementItemsCount: number | null;
  readonly payments: ReadonlyArray<Payment> | null;
  readonly payment: Payment | null;
  readonly paymentsCount: number | null;
  readonly imageStores: ReadonlyArray<ImageStore> | null;
  readonly imageStore: ImageStore | null;
  readonly imageStoresCount: number | null;
  readonly descriptionOfApprovals: ReadonlyArray<DescriptionOfApproval> | null;
  readonly descriptionOfApproval: DescriptionOfApproval | null;
  readonly descriptionOfApprovalsCount: number | null;
  readonly constractors: ReadonlyArray<Constractor> | null;
  readonly constractor: Constractor | null;
  readonly constractorsCount: number | null;
  readonly fileStores: ReadonlyArray<FileStore> | null;
  readonly fileStore: FileStore | null;
  readonly fileStoresCount: number | null;
  readonly contracts: ReadonlyArray<Contract> | null;
  readonly contract: Contract | null;
  readonly contractsCount: number | null;
  readonly designs: ReadonlyArray<Design> | null;
  readonly design: Design | null;
  readonly designsCount: number | null;
  readonly dailyReports: ReadonlyArray<DailyReport> | null;
  readonly dailyReport: DailyReport | null;
  readonly dailyReportsCount: number | null;
  readonly users: ReadonlyArray<User> | null;
  readonly user: User | null;
  readonly usersCount: number | null;
  readonly categories: ReadonlyArray<Category> | null;
  readonly category: Category | null;
  readonly categoriesCount: number | null;
  readonly logs: ReadonlyArray<Log> | null;
  readonly log: Log | null;
  readonly logsCount: number | null;
  readonly tags: ReadonlyArray<Tag> | null;
  readonly tag: Tag | null;
  readonly tagsCount: number | null;
  readonly keystone: KeystoneMeta;
  readonly authenticatedItem: AuthenticatedItem | null;
};

export type QueryapprovalsArgs = {
  readonly where?: ApprovalWhereInput;
  readonly orderBy?: TSGQLMaybeArray<ApprovalOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: ApprovalWhereUniqueInput | null;
};

export type QueryapprovalArgs = {
  readonly where: ApprovalWhereUniqueInput;
};

export type QueryapprovalsCountArgs = {
  readonly where?: ApprovalWhereInput;
};

export type QuerydescriptionsArgs = {
  readonly where?: DescriptionWhereInput;
  readonly orderBy?: TSGQLMaybeArray<DescriptionOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: DescriptionWhereUniqueInput | null;
};

export type QuerydescriptionArgs = {
  readonly where: DescriptionWhereUniqueInput;
};

export type QuerydescriptionsCountArgs = {
  readonly where?: DescriptionWhereInput;
};

export type QuerystatementsArgs = {
  readonly where?: StatementWhereInput;
  readonly orderBy?: TSGQLMaybeArray<StatementOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: StatementWhereUniqueInput | null;
};

export type QuerystatementArgs = {
  readonly where: StatementWhereUniqueInput;
};

export type QuerystatementsCountArgs = {
  readonly where?: StatementWhereInput;
};

export type QuerystatementItemsArgs = {
  readonly where?: StatementItemWhereInput;
  readonly orderBy?: TSGQLMaybeArray<StatementItemOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: StatementItemWhereUniqueInput | null;
};

export type QuerystatementItemArgs = {
  readonly where: StatementItemWhereUniqueInput;
};

export type QuerystatementItemsCountArgs = {
  readonly where?: StatementItemWhereInput;
};

export type QuerypaymentsArgs = {
  readonly where?: PaymentWhereInput;
  readonly orderBy?: TSGQLMaybeArray<PaymentOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: PaymentWhereUniqueInput | null;
};

export type QuerypaymentArgs = {
  readonly where: PaymentWhereUniqueInput;
};

export type QuerypaymentsCountArgs = {
  readonly where?: PaymentWhereInput;
};

export type QueryimageStoresArgs = {
  readonly where?: ImageStoreWhereInput;
  readonly orderBy?: TSGQLMaybeArray<ImageStoreOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: ImageStoreWhereUniqueInput | null;
};

export type QueryimageStoreArgs = {
  readonly where: ImageStoreWhereUniqueInput;
};

export type QueryimageStoresCountArgs = {
  readonly where?: ImageStoreWhereInput;
};

export type QuerydescriptionOfApprovalsArgs = {
  readonly where?: DescriptionOfApprovalWhereInput;
  readonly orderBy?: TSGQLMaybeArray<DescriptionOfApprovalOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: DescriptionOfApprovalWhereUniqueInput | null;
};

export type QuerydescriptionOfApprovalArgs = {
  readonly where: DescriptionOfApprovalWhereUniqueInput;
};

export type QuerydescriptionOfApprovalsCountArgs = {
  readonly where?: DescriptionOfApprovalWhereInput;
};

export type QueryconstractorsArgs = {
  readonly where?: ConstractorWhereInput;
  readonly orderBy?: TSGQLMaybeArray<ConstractorOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: ConstractorWhereUniqueInput | null;
};

export type QueryconstractorArgs = {
  readonly where: ConstractorWhereUniqueInput;
};

export type QueryconstractorsCountArgs = {
  readonly where?: ConstractorWhereInput;
};

export type QueryfileStoresArgs = {
  readonly where?: FileStoreWhereInput;
  readonly orderBy?: TSGQLMaybeArray<FileStoreOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: FileStoreWhereUniqueInput | null;
};

export type QueryfileStoreArgs = {
  readonly where: FileStoreWhereUniqueInput;
};

export type QueryfileStoresCountArgs = {
  readonly where?: FileStoreWhereInput;
};

export type QuerycontractsArgs = {
  readonly where?: ContractWhereInput;
  readonly orderBy?: TSGQLMaybeArray<ContractOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: ContractWhereUniqueInput | null;
};

export type QuerycontractArgs = {
  readonly where: ContractWhereUniqueInput;
};

export type QuerycontractsCountArgs = {
  readonly where?: ContractWhereInput;
};

export type QuerydesignsArgs = {
  readonly where?: DesignWhereInput;
  readonly orderBy?: TSGQLMaybeArray<DesignOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: DesignWhereUniqueInput | null;
};

export type QuerydesignArgs = {
  readonly where: DesignWhereUniqueInput;
};

export type QuerydesignsCountArgs = {
  readonly where?: DesignWhereInput;
};

export type QuerydailyReportsArgs = {
  readonly where?: DailyReportWhereInput;
  readonly orderBy?: TSGQLMaybeArray<DailyReportOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: DailyReportWhereUniqueInput | null;
};

export type QuerydailyReportArgs = {
  readonly where: DailyReportWhereUniqueInput;
};

export type QuerydailyReportsCountArgs = {
  readonly where?: DailyReportWhereInput;
};

export type QueryusersArgs = {
  readonly where?: UserWhereInput;
  readonly orderBy?: TSGQLMaybeArray<UserOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: UserWhereUniqueInput | null;
};

export type QueryuserArgs = {
  readonly where: UserWhereUniqueInput;
};

export type QueryusersCountArgs = {
  readonly where?: UserWhereInput;
};

export type QuerycategoriesArgs = {
  readonly where?: CategoryWhereInput;
  readonly orderBy?: TSGQLMaybeArray<CategoryOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: CategoryWhereUniqueInput | null;
};

export type QuerycategoryArgs = {
  readonly where: CategoryWhereUniqueInput;
};

export type QuerycategoriesCountArgs = {
  readonly where?: CategoryWhereInput;
};

export type QuerylogsArgs = {
  readonly where?: LogWhereInput;
  readonly orderBy?: TSGQLMaybeArray<LogOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: LogWhereUniqueInput | null;
};

export type QuerylogArgs = {
  readonly where: LogWhereUniqueInput;
};

export type QuerylogsCountArgs = {
  readonly where?: LogWhereInput;
};

export type QuerytagsArgs = {
  readonly where?: TagWhereInput;
  readonly orderBy?: TSGQLMaybeArray<TagOrderByInput>;
  readonly take?: number | null;
  readonly skip?: number;
  readonly cursor?: TagWhereUniqueInput | null;
};

export type QuerytagArgs = {
  readonly where: TagWhereUniqueInput;
};

export type QuerytagsCountArgs = {
  readonly where?: TagWhereInput;
};

export type AuthenticatedItem = User;

export type KeystoneMeta = {
  readonly __typename: "KeystoneMeta";
  readonly adminMeta: KeystoneAdminMeta;
};

export type KeystoneAdminMeta = {
  readonly __typename: "KeystoneAdminMeta";
  readonly lists: ReadonlyArray<KeystoneAdminUIListMeta>;
  readonly list: KeystoneAdminUIListMeta | null;
};

export type KeystoneAdminMetalistArgs = {
  readonly key: string;
};

export type KeystoneAdminUIListMeta = {
  readonly __typename: "KeystoneAdminUIListMeta";
  readonly key: string;
  readonly itemQueryName: string;
  readonly listQueryName: string;
  readonly hideCreate: boolean;
  readonly hideDelete: boolean;
  readonly path: string;
  readonly label: string;
  readonly singular: string;
  readonly plural: string;
  readonly description: string | null;
  readonly initialColumns: ReadonlyArray<string>;
  readonly pageSize: number;
  readonly labelField: string;
  readonly fields: ReadonlyArray<KeystoneAdminUIFieldMeta>;
  readonly groups: ReadonlyArray<KeystoneAdminUIFieldGroupMeta>;
  readonly initialSort: KeystoneAdminUISort | null;
  readonly isHidden: boolean;
  readonly isSingleton: boolean;
};

export type KeystoneAdminUIFieldMeta = {
  readonly __typename: "KeystoneAdminUIFieldMeta";
  readonly path: string;
  readonly label: string;
  readonly description: string | null;
  readonly isOrderable: boolean;
  readonly isFilterable: boolean;
  readonly isNonNull: ReadonlyArray<KeystoneAdminUIFieldMetaIsNonNull> | null;
  readonly fieldMeta: JSON | null;
  readonly viewsIndex: number;
  readonly customViewsIndex: number | null;
  readonly createView: KeystoneAdminUIFieldMetaCreateView;
  readonly listView: KeystoneAdminUIFieldMetaListView;
  readonly itemView: KeystoneAdminUIFieldMetaItemView | null;
  readonly search: QueryMode | null;
};

export type KeystoneAdminUIFieldMetaitemViewArgs = {
  readonly id?: string | null;
};

export type KeystoneAdminUIFieldMetaIsNonNull =
  | "read"
  | "create"
  | "update";

export type KeystoneAdminUIFieldMetaCreateView = {
  readonly __typename: "KeystoneAdminUIFieldMetaCreateView";
  readonly fieldMode: KeystoneAdminUIFieldMetaCreateViewFieldMode;
};

export type KeystoneAdminUIFieldMetaCreateViewFieldMode =
  | "edit"
  | "hidden";

export type KeystoneAdminUIFieldMetaListView = {
  readonly __typename: "KeystoneAdminUIFieldMetaListView";
  readonly fieldMode: KeystoneAdminUIFieldMetaListViewFieldMode;
};

export type KeystoneAdminUIFieldMetaListViewFieldMode =
  | "read"
  | "hidden";

export type KeystoneAdminUIFieldMetaItemView = {
  readonly __typename: "KeystoneAdminUIFieldMetaItemView";
  readonly fieldMode: KeystoneAdminUIFieldMetaItemViewFieldMode | null;
  readonly fieldPosition: KeystoneAdminUIFieldMetaItemViewFieldPosition | null;
};

export type KeystoneAdminUIFieldMetaItemViewFieldMode =
  | "edit"
  | "read"
  | "hidden";

export type KeystoneAdminUIFieldMetaItemViewFieldPosition =
  | "form"
  | "sidebar";

export type QueryMode =
  | "default"
  | "insensitive";

export type KeystoneAdminUIFieldGroupMeta = {
  readonly __typename: "KeystoneAdminUIFieldGroupMeta";
  readonly label: string;
  readonly description: string | null;
  readonly fields: ReadonlyArray<KeystoneAdminUIFieldMeta>;
};

export type KeystoneAdminUISort = {
  readonly __typename: "KeystoneAdminUISort";
  readonly field: string;
  readonly direction: KeystoneAdminUISortDirection;
};

export type KeystoneAdminUISortDirection =
  | "ASC"
  | "DESC";

type TSGQLMaybeArray<T> = ReadonlyArray<T> | T

export {};
export interface TSGQLDocuments extends Record<string, import('@ts-gql/tag').TypedDocumentNode<import('@ts-gql/tag').BaseDocumentTypes>> {}

export type TSGQLRequiredFragments<T> = (providedFragments: T) => T;